// <auto-generated />
using System;
using Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.Entities.Gender", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Genders", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "Action",
                            Id = 0
                        },
                        new
                        {
                            Name = "Drama",
                            Id = 0
                        },
                        new
                        {
                            Name = "Comedy",
                            Id = 0
                        });
                });

            modelBuilder.Entity("Database.Entities.Producer", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Producers", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "Netflix",
                            Id = 0
                        },
                        new
                        {
                            Name = "HBO",
                            Id = 0
                        },
                        new
                        {
                            Name = "Amazon Prime",
                            Id = 0
                        });
                });

            modelBuilder.Entity("Database.Entities.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateLaunch")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenderName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProducerName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GenderName");

                    b.HasIndex("ProducerName");

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("Database.Entities.Serie", b =>
                {
                    b.HasOne("Database.Entities.Gender", "Gender")
                        .WithMany("Series")
                        .HasForeignKey("GenderName")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Database.Entities.Producer", "Producer")
                        .WithMany("Series")
                        .HasForeignKey("ProducerName");

                    b.Navigation("Gender");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("Database.Entities.Gender", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("Database.Entities.Producer", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
